### PR TITLE
Kdb4 merge

### PR DESCRIPTION
**Pull request by crass**
Here is some KDB merge code that I've finally gotten to the point of wanting to do a pull request.  I realize that things are moving over to pykeepass, but I think this will still be useful to libkeepass users.  There are a decent amount of tests for the merge code as well.

I suspect that a lot of the merge code will work with pykeepass with few modifications since it operates on the xml elements.  But I haven't looked very far into this.

### CODE REVIEW

**Comment by graingert** [comment]
@Evidlo any chance of a release of this version?

**Comment by Evidlo** [comment]
@graingert Done

**Comment by graingert** [comment]
Can you add it here too @Evidlo https://github.com/libkeepass/libkeepass/releases

**Comment by Evidlo** [comment]
@graingert done

**Pull request merged**
