### PR TITLE
Remove twofish support because of outdated CryptoPlus library

### PR DESCRIPTION
**Pull request by firecat53**
So, just going off @Evidlo's comment in #12, here's a PR to remove twofish and CryptoPlus support.

I'll leave it to the more experienced members here to decide if that's actually a good idea! Figured I'd supply the grunt work...seemed easy enough.

Thanks!
Scott

### CODE REVIEW

**Comment by Evidlo** [comment]
Could you show a warning that TwoFish support has been removed? (and replace the test with a check for this warning, see `test_open_file_protected` for example)

**Comment by firecat53** [comment]
@Evidlo - sorry for the delay. Where/when is a good place to show the warning?

**Comment by Evidlo** [comment]
The elif statements you deleted in `kdb3.py` and `kdb4.py` would be a good spot.

**Comment by firecat53** [comment]
@Evidlo - done. Let me know if that's not what you had in mind.

**Comment by Evidlo** [comment]
Looks good.  Why do you think those exceptions should be removed next release though?

**Comment by firecat53** [comment]
It seems to me that at some point, twofish should just be treated as an unsupported encryption option and the special notification should be unnecessary. However... That's just my uneducated opinion. If there are reasons why it should always have that warning, I'm happy to remove those comments!

**Pull request merged**
